// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLog(arg1, arg2) {
  return window['go']['main']['App']['AddLog'](arg1, arg2);
}

export function AddLogWithDetails(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddLogWithDetails'](arg1, arg2, arg3);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ClearTempScanResults() {
  return window['go']['main']['App']['ClearTempScanResults']();
}

export function ExecuteCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteCommand'](arg1, arg2);
}

export function ExportLogsToFile() {
  return window['go']['main']['App']['ExportLogsToFile']();
}

export function ExportResultsToExcel(arg1) {
  return window['go']['main']['App']['ExportResultsToExcel'](arg1);
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetMemoryShellTypes(arg1) {
  return window['go']['main']['App']['GetMemoryShellTypes'](arg1);
}

export function GetProxyConfig() {
  return window['go']['main']['App']['GetProxyConfig']();
}

export function GetScanProgress() {
  return window['go']['main']['App']['GetScanProgress']();
}

export function GetSupportedVulnerabilityTypes() {
  return window['go']['main']['App']['GetSupportedVulnerabilityTypes']();
}

export function GetTempScanResults() {
  return window['go']['main']['App']['GetTempScanResults']();
}

export function GetVulnerabilityTypeLabels() {
  return window['go']['main']['App']['GetVulnerabilityTypeLabels']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InjectMemoryShell(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InjectMemoryShell'](arg1, arg2, arg3, arg4);
}

export function SetProxyConfig(arg1) {
  return window['go']['main']['App']['SetProxyConfig'](arg1);
}

export function StartReverseShell(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartReverseShell'](arg1, arg2, arg3);
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}

export function TestConnection(arg1, arg2) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2);
}
