// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddLog(arg1:string,arg2:string):Promise<void>;

export function AddLogWithDetails(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function ClearLogs():Promise<void>;

export function ClearTempScanResults():Promise<void>;

export function ExecuteCommand(arg1:number,arg2:string):Promise<string>;

export function ExportLogsToFile():Promise<string>;

export function ExportResultsToExcel(arg1:Array<main.Vulnerability>):Promise<string>;

export function GetLogs():Promise<Array<main.LogEntry>>;

export function GetMemoryShellTypes(arg1:number):Promise<Array<Record<string, string>>>;

export function GetProxyConfig():Promise<main.ProxyConfig>;

export function GetScanProgress():Promise<number>;

export function GetSupportedVulnerabilityTypes():Promise<Array<string>>;

export function GetTempScanResults():Promise<Array<main.Vulnerability>>;

export function GetVulnerabilityTypeLabels():Promise<Record<string, string>>;

export function Greet(arg1:string):Promise<string>;

export function InjectMemoryShell(arg1:number,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SetProxyConfig(arg1:main.ProxyConfig):Promise<void>;

export function StartReverseShell(arg1:number,arg2:string,arg3:string):Promise<string>;

export function StartScan(arg1:main.ScanOptions):Promise<Array<main.Vulnerability>>;

export function StopScan():Promise<void>;

export function TestConnection(arg1:string,arg2:main.ProxyConfig):Promise<boolean|string>;
